name: 'Microsoft Teams Workflows Webhook Message'
description: 'Posts an adaptive card to a Microsoft Teams channel via a webhook'
author: 'Michael Gaver-Holmes'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  webhook-url:
    description: 'The workflow URL to post the message to'
    required: true
  body:
    description: 'The body of the message to post, as YAML'
    required: true

# Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
